# Use the latest Windows Server Core image with .NET Framework 4.8.
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

# Restore the default Windows shell for correct batch processing.
SHELL ["cmd", "/S", "/C"]

# create folder for build tools
RUN MD C:\BuildTools

# add vc_redist.x64.exe for VS2015 and install it quietly
ADD https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe C:/BuildTools/vc_redist.x64.exe
RUN C:\BuildTools\vc_redist.x64.exe /quiet /install
#RUN DEL C:\BuildTools\vc_redist.x64.exe

# Download Visual Studio 2019 Build Tools EXE
ADD https://aka.ms/vs/16/release/vs_buildtools.exe C:/BuildTools/vs_buildtools.exe

# Install Build Tools excluding workloads and components with known issues.
RUN C:\BuildTools\vs_buildtools.exe --installPath C:/vs --quiet --wait --norestart --nocache --includeRecommended --includeOptional --all

# Install Visual Studio 2019 Build Tools
#RUN C:\BuildTools\vs_buildtools.exe --installPath C:/vs --quiet --wait --norestart --nocache --includeRecommended --includeOptional
# --add Microsoft.VisualStudio.Workload.NativeDesktop
#--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools --add Microsoft.VisualStudio.Workload.MSBuildTools --add Microsoft.VisualStudio.Workload.OfficeBuildTools
#RUN DEL C:\BuildTools\vs_buildtools.exe

# download 7z for unzip
ADD https://www.7-zip.org/a/7z1900-x64.exe C:/BuildTools/7z1900-x64.exe
RUN C:\BuildTools\7z1900-x64.exe /S /D="C:\7z"
#RUN DEL C:\BuildTools\7z1900-x64.exe

# download CMake and unzip package
ADD https://github.com/Kitware/CMake/releases/download/v3.15.4/cmake-3.15.4-win64-x64.zip C:/BuildTools/cmake-win64-x64.zip
RUN MD C:\cmake
RUN C:\7z\7z.exe x -oC:\cmake C:/BuildTools/cmake-win64-x64.zip
RUN setx -m PATH "%PATH%;C:\cmake\cmake-3.15.4-win64-x64\bin"
#RUN DEL C:\BuildTools\cmake-win64-x64.zip

# download YASM
RUN MD C:\yasm
ADD http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe C:/yasm/yasm.exe
RUN setx -m PATH "%PATH%;C:\yasm"

#RUN setx -m EnterpriseWDK "True"
#RUN setx -m DisableRegistryUse "True"

# Start Visual Studio 2019 Developer Command Prompt
ENTRYPOINT C:/vs/Common7/Tools/VsDevCmd.bat && cmd.exe
